---
title       : Test Slides
subtitle    : with slidify and Rmd
author      : Kevin Middleton
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]
mode        : selfcontained # {standalone, draft}
github:
  user: kmiddleton
  repo: testslides

```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}
# make this an external chunk that can be included in any file
options(width = 70)
opts_chunk$set(message = FALSE, 
               error = FALSE, 
               warning = FALSE, 
               echo = FALSE, 
               comment = NA, 
               fig.align = 'center', 
               dpi = 100, 
#               fig.height = 4.5, 
#               fig.width = 8, 
               tidy = FALSE, 
               cache = FALSE, 
               fig.path = 'fig/')
require(ggplot2)
require(xtable)
require(plyr)
require(openintro)
options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
knit_hooks$set(plot = knitr:::hook_plot_html)
require(latticeExtra)
trellis.par.set(theme = theEconomist.theme(box = 'transparent'))
lattice.options(theEconomist.opts())
knit_hooks$set(document = function(doc){
  stringr::str_replace_all(doc, "```\n*```[^r]", "")
})
```

--- .segue .quote .dark

<q> Slidify is a tool that makes it easy to create, customize and publish, reproducible HTML5 slide decks using R Markdown.</q>

<style>
.dark q {
  color: white;
}
</style>

--- .middle

## Read-And-Delete

1. Edit YAML front matter
2. Write using R Markdown
3. Use an empty line followed by three dashes to separate slides!

--- .class #id 

## A Simple Plot

Let us create a simple scatterplot.

```{r simple-plot, fig.height = 6, fig.align = 'center', message = F}
require(ggplot2)
qplot(wt, mpg, data = mtcars)
```

--- 

## A Table

```{r table, results = 'asis', comment = NA}
library(xtable)
options(xtable.type = 'html')
xtable(head(mtcars))
```

---

## Mathjax ##

$$
\begin{aligned}
\nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} & = \frac{4\pi}{c}\vec{\mathbf{j}} \\   \nabla \cdot \vec{\mathbf{E}} & = 4 \pi \rho \\
\nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} & = \vec{\mathbf{0}} \\
\nabla \cdot \vec{\mathbf{B}} & = 0 \end{aligned}
$$
<br />
$$
\mathbf{V}_1 \times \mathbf{V}_2 =  \begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
\frac{\partial X}{\partial u} &  \frac{\partial Y}{\partial u} & 0 \\
\frac{\partial X}{\partial v} &  \frac{\partial Y}{\partial v} & 0
\end{vmatrix}
$$
